# Templated by `cargo-generate` using https://github.com/danielhenrymantilla/proc-macro-template

[lib]
name = "lending_iterator"
path = "src/_lib.rs"

[package]
name = "lending-iterator"
authors = [
    "Daniel Henry-Mantilla <daniel.henry.mantilla@gmail.com>",
]
version = "0.1.0-rc1"  # Keep in sync
edition = "2021"

license = "Zlib OR MIT OR Apache-2.0"
repository = "https://github.com/danielhenrymantilla/lending-iterator.rs"
documentation = "https://docs.rs/lending-iterator"
readme = "README.md"

# description = "…"
# keywords = []

[features]
better-docs = []  # allowed to break MSRV
ui-tests = ["better-docs"]

[dependencies]
higher-order-closure.version = "0.0.5"
higher-order-closure.path = "../higher-order-closure.rs"

macro_rules_attribute.version = "0.1.1"
macro_rules_attribute.path = "../macro_rules_attribute-rs"

nougat.version = "0.2.0-rc1"
nougat.path = "../nougat.rs"

polonius-the-crab.version = "0.2.2-rc1"
polonius-the-crab.path = "../polonius-the-crab.rs"

[dev-dependencies]

[workspace]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--html-before-content", "fix-docsrs-li-details-summary.html",
]
